### ISSUE TITLE
Would it be possible to release the train.py ?

### ISSUE THREAD

**Issue by Sissuire** [GZHU-DVL/TiVQA#1]
or, how to train a separate model with the given `TiVQA.py` on my dataset?

**Comment by GZHU-DVL** [comment]
Thank you very much for your attention to our work. I am very sorry that I have not logged in to github recently. If you have any questions, you can write an email directly. The training code of this work will be released soon. Thank you again for your attention.

**Comment by Sissuire** [comment]
@GZHU-DVL Good. Thank you for sharing.
